# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_dispatch: {}

permissions:
  contents: read
    
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
        contents: read      # To read repo data 
        issues: write       # To read and write issues
        id-token: write     # To mint signing tokens
        attestations: write # Push attested VEX data to the attestations store
      
    steps:
        - name: Setup vexflow
          uses: carabiner-dev/actions/install/vexflow@HEAD
        - run: |
            vexflow update carabiner-dev/ampel
